"""Non-LLM MAF Workflow for local Azure Functions + MSSQL Durable provider.

No model secrets, no shell tools, and no production business effects.
The filesystem markers are independent test observers, not runtime state.
"""
import os
import re
from pathlib import Path
from typing import Never

from agent_framework import (
    Executor, WorkflowBuilder, WorkflowContext, handler, response_handler,
)
import azure.functions as func
from agent_framework_azurefunctions import AgentFunctionApp

WORKFLOW_NAME = "maf_mssql_poc_hitl"

# Generated by trusted local fixture; restrict filename and HITL request input.
CASE_PATTERN = re.compile(r"(?:approved|rejected)-fixture-[0-9a-f]{12}\Z")


def mark(case: str, phase: str) -> None:
    if not CASE_PATTERN.fullmatch(case):
        raise ValueError("Untrusted fixture")
    root = Path(os.environ["POC_MARKER_DIR"])
    root.mkdir(parents=True, exist_ok=True)
    with (root / f"{case}.{phase}").open("a", encoding="utf-8") as f:
        f.write("1\n")


class Prepare(Executor):
    @handler
    async def prepare(self, case: str, ctx: WorkflowContext[str]) -> None:
        mark(case, "prepare")
        await ctx.send_message(case)


class Approval(Executor):
    @handler
    async def ask(self, case: str, ctx: WorkflowContext[str, str]) -> None:
        if not CASE_PATTERN.fullmatch(case):
            raise ValueError("Unknown fixture")
        await ctx.request_info(
            request_data=f"approval:{case}",
            response_type=str,
        )

    @response_handler
    async def decide(
        self, original_request: str, response: str,
        ctx: WorkflowContext[str, str],
    ) -> None:
        if not original_request.startswith("approval:"):
            raise ValueError("Unknown request")
        case = original_request.split(":", 1)[1]
        if not CASE_PATTERN.fullmatch(case):
            raise ValueError("Unknown fixture")
        if response == "APPROVED":
            await ctx.send_message(case)
        elif response == "REJECTED":
            await ctx.yield_output("DENIED_NO_EXECUTION")
        else:
            raise ValueError("Unknown decision")


class SimulatedExecution(Executor):
    @handler
    async def run_approved_action(self, case: str, ctx: WorkflowContext[Never, str]) -> None:
        mark(case, "action")
        await ctx.yield_output(f"SIMULATED_EXECUTION:{case}")


def build_workflow():
    a = Prepare(id="prepare")
    b = Approval(id="approval")
    c = SimulatedExecution(id="simulated_sensitive_action")
    return (
        WorkflowBuilder(name=WORKFLOW_NAME, start_executor=a)
        .add_edge(a, b)
        .add_edge(b, c)
        .build()
    )


# Only on the loopback-bound, isolated Docker POC. Never use ANONYMOUS in production.
app = AgentFunctionApp(workflow=build_workflow(), enable_health_check=True, http_auth_level=func.AuthLevel.ANONYMOUS)
