"""Non-LLM MAF Workflow for local Azure Functions + MSSQL Durable provider.

No model secrets, no shell tools, and no production business effects.
The filesystem markers are independent test observers, not runtime state.
"""
import os
import asyncio
import re
import json
from urllib import request as http_request, error as http_error
from pathlib import Path
from typing import Never

from agent_framework import (
    Executor, WorkflowBuilder, WorkflowContext, handler, response_handler,
)
import azure.functions as func
from agent_framework_azurefunctions import AgentFunctionApp

WORKFLOW_NAME = "maf_mssql_poc_hitl"
# Frozen application contract; a different-image Worker must declare its own version.
WORKER_GUARDED_WORKFLOW_VERSION = "maf_mssql_poc_guarded:v1"

# Generated by trusted local fixture; restrict filename and HITL request input.
CASE_PATTERN = re.compile(r"(?:approved|rejected|running|guarded)-fixture-[0-9a-f]{12}\Z")


def mark(case: str, phase: str) -> None:
    if not CASE_PATTERN.fullmatch(case):
        raise ValueError("Untrusted fixture")
    root = Path(os.environ["POC_MARKER_DIR"])
    root.mkdir(parents=True, exist_ok=True)
    with (root / f"{case}.{phase}").open("a", encoding="utf-8") as f:
        f.write("1\n")


class Prepare(Executor):
    @handler
    async def prepare(self, case: str, ctx: WorkflowContext[str]) -> None:
        mark(case, "prepare")
        if os.environ.get("POC_RUNNING_GUARDED") == "1":
            # Native Instance ID must be bound to the platform before tool admission.
            delay = int(os.environ.get("POC_VERSION_PREPARE_DELAY_SECONDS", "12"))
            if not 0 <= delay <= 90:
                raise ValueError("Untrusted prepare delay")
            await asyncio.sleep(delay)
        await ctx.send_message(case)


class Approval(Executor):
    @handler
    async def ask(self, case: str, ctx: WorkflowContext[str, str]) -> None:
        if not CASE_PATTERN.fullmatch(case):
            raise ValueError("Unknown fixture")
        await ctx.request_info(
            request_data=f"approval:{case}",
            response_type=str,
        )

    @response_handler
    async def decide(
        self, original_request: str, response: str,
        ctx: WorkflowContext[str, str],
    ) -> None:
        if not original_request.startswith("approval:"):
            raise ValueError("Unknown request")
        case = original_request.split(":", 1)[1]
        if not CASE_PATTERN.fullmatch(case):
            raise ValueError("Unknown fixture")
        if response == "APPROVED":
            await ctx.send_message(case)
        elif response == "REJECTED":
            await ctx.yield_output("DENIED_NO_EXECUTION")
        else:
            raise ValueError("Unknown decision")


class SimulatedExecution(Executor):
    @handler
    async def run_approved_action(self, case: str, ctx: WorkflowContext[Never, str]) -> None:
        mark(case, "action")
        await ctx.yield_output(f"SIMULATED_EXECUTION:{case}")


def build_workflow():
    a = Prepare(id="prepare")
    b = Approval(id="approval")
    c = SimulatedExecution(id="simulated_sensitive_action")
    return (
        WorkflowBuilder(name=WORKFLOW_NAME, start_executor=a)
        .add_edge(a, b)
        .add_edge(b, c)
        .build()
    )


# A34 execution-in-flight probe, isolated from the normal HITL Workflow.
# Markers are observers, not real external business side effects or idempotency.
class RunningExecutionProbe(Executor):
    @handler
    async def run_long(self, case: str, ctx: WorkflowContext[Never, str]) -> None:
        if not case.startswith("running-fixture-") or not CASE_PATTERN.fullmatch(case):
            raise ValueError("Untrusted running fixture")
        seconds = int(os.environ.get("POC_RUNNING_DELAY_SECONDS", "75"))
        if not 30 <= seconds <= 120:
            raise ValueError("Running probe delay outside test bounds")
        mark(case, "dispatch_observed")
        await asyncio.sleep(seconds)
        mark(case, "completed_observed")
        await ctx.yield_output(f"SIMULATED_RUNNING:{case}")


def build_running_workflow():
    a = Prepare(id="prepare")
    b = RunningExecutionProbe(id="running_execution_probe")
    return (WorkflowBuilder(name="maf_mssql_poc_running", start_executor=a)
            .add_edge(a, b).build())


# A34 combined native-MSSQL / Harness-PG crash probe.
# The host-side fixture gateway owns the PG admission transaction and
# independent tool-sink receipt. The Worker never receives a PG password.
class GuardedRunningExecutionProbe(Executor):
    @handler
    async def run_guarded(self, case: str, ctx: WorkflowContext[Never, str]) -> None:
        if not case.startswith("guarded-fixture-") or not CASE_PATTERN.fullmatch(case):
            raise ValueError("Untrusted guarded fixture")
        mark(case, "guarded_dispatch_entered")
        root = Path(os.environ["POC_MARKER_DIR"])
        token = (root / (case + ".gateway_token")).read_text(encoding="utf-8").strip()
        target = os.environ["POC_GUARDED_GATEWAY_URL"]
        if target != "http://host.docker.internal:17105/admit":
            raise ValueError("Untrusted test gateway")
        req = http_request.Request(
            target,
            data=json.dumps({"case": case}).encode("utf-8"),
            headers={"Content-Type": "application/json", "X-POC-Token": token,
                     "X-POC-Worker-Workflow-Version": WORKER_GUARDED_WORKFLOW_VERSION},
            method="POST",
        )
        try:
            with http_request.urlopen(req, timeout=15) as response:
                if response.status != 200:
                    raise RuntimeError("Admission gateway returned non-200")
        except http_error.HTTPError as error:
            if error.code == 412:
                mark(case, "guarded_version_denied")
                raise RuntimeError("HARNESS_INCOMPATIBLE_WORKER_VERSION") from error
            if error.code == 409:
                mark(case, "guarded_admission_denied")
                raise RuntimeError("HARNESS_TOOL_REPLAY_DENIED") from error
            raise
        mark(case, "guarded_admission_applied")
        await asyncio.sleep(95)
        mark(case, "guarded_completed_after_tool")
        await ctx.yield_output(f"GUARDED_RUNNING:{case}")


def build_guarded_running_workflow():
    a = Prepare(id="prepare")
    b = GuardedRunningExecutionProbe(id="guarded_running_execution")
    return WorkflowBuilder(
        name="maf_mssql_poc_guarded", start_executor=a
    ).add_edge(a, b).build()


# Only on the loopback-bound isolated Docker POC. Never use ANONYMOUS in production.
probe = os.environ.get("POC_RUNNING_PROBE") == "1"
guarded = os.environ.get("POC_RUNNING_GUARDED") == "1"
app = AgentFunctionApp(
    workflow=build_guarded_running_workflow() if guarded else (
        build_running_workflow() if probe else build_workflow()
    ),
    enable_health_check=True, http_auth_level=func.AuthLevel.ANONYMOUS,
)
